### ISSUE TITLE
Readme Needs Updates!

### ISSUE THREAD

**Issue by Miss-Lonelyhearts** [openc2e/openc2e#143]
Hey! Very excited to see so much new activity on this project-- I was sad when it was abandoned years ago.
One important issue however-- the **readme is identical to the old one** making it seem as though the project has not progressed. Looking at committs, **it clearly has moved on a lot**, nice work! 

If you could help me understand the important fixes/updates, I will write a better Readme that updates the project information. If you're open to this idea, I'll do a detailed write-up of the "Status" section with a focus on getting the "Working" items apparent while showing potential contributors what's still in-progress or non-functional. I'd also like to get started on writing a better "About" section that sells the engine better to incite and re-ignite interest. Once that's done, I'll aim to get the word out to people who were playing the Creatures games (many/most of the communities look to have died down, but a project like this one could change everthing)!

If you update me on what you think the key committs have been since the project's been updated, I'll start a draft of the Readme. 

I'd love to contribute through writing this readme and doing bug-testing. I am not a coder, but I would like to contribute! Let me know if there's anything else I can do.

**Comment by ligfx** [comment]
Thanks @Miss-Lonelyhearts — can you hop on the Discord to discuss further? https://discord.gg/2rxYVj

**Comment by Miss-Lonelyhearts** [comment]
> Thanks @Miss-Lonelyhearts — can you hop on the Discord to discuss further? https://discord.gg/rWFC3b3

Sure, I will hop on after work today.
