### ISSUE TITLE
commandinfo.json (generated file) typos.

### ISSUE THREAD

**Issue by gantt42** [openc2e/openc2e#166]
commandinfo.json has two known types of typos.
 - "any" is incorrect; it should be "anything".
 - Either "byte-string" or "bytestring" is incorrect; it should be just one of them.
   - According to ligfx it should be "bytestring", but in the CAOS html file generated by original engine, it's "byte-string".

**Comment by gantt42** [comment]
In my opinion, "byte-string" would be slightly better. But not by much and I won't argue much for the point.

**Comment by ligfx** [comment]
This was already fixed in 8a759d9 and d3f0d6d
