### ISSUE TITLE
Incorrectly included CV commands

### ISSUE THREAD

**Issue by bedalton** [openc2e/openc2e#179]
Commands are not in CV docs, but they may still be valid. I do not have access to this game, so cannot test commands.

Listed variant c2 cv c3 sm
- [ ] CALL - marked variant c2 cv c3 sm
- [ ] ISCR - marked variant c2 cv c3 sm
- [ ] RSCR - Variant c2 cv c3 sm

Marked variant all
- [ ] DBG: DISA
- [ ] DBG: DUMP
- [ ] DBG: SIZO
- [ ] DBG: STOK
- [ ] DBG: TRACE - Guessing this is OpenC2e-only
- [ ] DBG: TSLC (command)
- [ ] DBG: TSLC (integer)
- [ ] DCOR
- [ ] MODU
- [ ] WRAP

I am mostly comparing a document I saw on another GitHub project, StoryTeller, that listed data about the OpenC2e commands with various other data in a document called commandinfo.json,  located [here]https://github.com/gantt42/Storyteller/blob/master/caos-tool-window/parser/commandinfo.json) that the author mentioned he got from someone in the OpenC2e project.  In that document, some commands are listed in the CV variant, but in the OpenC2e codebase, they have no specific variant listed. These are the commands with no specific variant that appear in that document under variant.cv:
- [ ] ABBA
- [ ] ADMP (command)
- [ ] ADMP (float)
- [ ] ANGL
- [ ] AVEL (command)
- [ ] AVEL (float)
- [ ] BUZZ (command)
- [ ] BUZZ (integer)
- [ ] CATA
- [ ] CATO
- [ ] CORE
- [ ] DBG: MALLOC - Not marked as OpenC2e-only, but I am guessing it is
- [ ] DBG: SBGM
- [ ] DBG: SINE
- [ ] DELN
- [ ] DOIN
- [ ] EAME
- [ ] FACE INT
- [ ] FACE STRING
- [ ] FDMP
- [ ] FDMP
- [ ] FVEL
- [ ] FVEL
- [ ] GALL
- [ ] HIST NETU
- [ ] HIST WVET
- [ ] HOTP
- [ ] JECT
- [ ] LIMB
- [ ] LOWA
- [ ] MAME
- [ ] MIND (command)
- [ ] MIND (integer)
- [ ] MOTR (command)
- [ ] MOTR
- [ ] NAME
- [ ] NAMN
- [ ] NET: ERRA
- [ ] NET: EXPO
- [ ] NET: FROM
- [ ] NET: HEAD
- [ ] NET: HEAR
- [ ] NET: HOST
- [ ] NET: LINE
- [ ] NET: LINE
- [ ] NET: MAKE
- [ ] NET: PASS
- [ ] NET: PASS
- [ ] NET: RAWE
- [ ] NET: RUSO
- [ ] NET: STAT
- [ ] NET: ULIN
- [ ] NET: UNIK
- [ ] NET: USER
- [ ] NET: WHAT
- [ ] NET: WHOD
- [ ] NET: WHOF
- [ ] NET: WHON
- [ ] NET: WHOZ
- [ ] NET: WRIT
- [ ] PAGE
- [ ] PART
- [ ] PAT: MOVE
- [ ] PNXT
- [ ] PRAY BACK
- [ ] PRAY FORE
- [ ] PRAY KILL
- [ ] ROTN
- [ ] SDMP
- [ ] SDMP
- [ ] SEEN
- [ ] SERL MAPP
- [ ] SERL SCRP
- [ ] SERS MAPP
- [ ] SERS SCRP
- [ ] SINS
- [ ] SOUL
- [ ] SOUL
- [ ] SPIN
- [ ] SPIN
- [ ] STEP
- [ ] STRC
- [ ] SVEL
- [ ] SVEL
- [ ] TCOR
- [ ] TINO
- [ ] TINT
- [ ] UFOS
- [ ] UPPA
- [ ] VOLM
- [ ] WEBB

**Comment by ligfx** [comment]
Hmm. We can probably assume that in general, commands that work in C3 will also work in CV. I'm going to mark the openc2e-only commands though, so there's no confusion.
