### ISSUE TITLE
Creatures 3 source code.

### ISSUE THREAD

**Issue by ArekReve** [openc2e/openc2e#197]
Hi. Maybe it will be helpful for your project. The source code for part 3 was released some time ago on github.

https://github.com/videogamepreservation/creatures3

**Comment by hogsy** [comment]
I think for legal reasons they would probably do best to avoid using the original source code as reference given it's not released under any explicit license.

**Comment by ligfx** [comment]
Correct, we cannot use any proprietary source code. openc2e is licensed under LGPL.
